# Generated by Django 6.0.8 on 2026-09-13 20:52

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(db_index=True, max_length=128)),
                ('event_type', models.CharField(choices=[('session_start', 'Session Start'), ('homepage_view', 'Homepage View'), ('category_view', 'Category View'), ('search', 'Search Query Entered'), ('search_result_view', 'Search Results Viewed'), ('filter_used', 'Filter Applied'), ('sort_used', 'Sort Applied'), ('product_view', 'Product Detail View'), ('wishlist_add', 'Added to Wishlist'), ('wishlist_remove', 'Removed from Wishlist'), ('add_to_cart', 'Added to Cart'), ('remove_from_cart', 'Removed from Cart'), ('checkout_started', 'Checkout Started'), ('checkout_abandoned', 'Checkout Abandoned'), ('purchase_completed', 'Purchase Completed')], db_index=True, max_length=64)),
                ('search_query', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('device_type', models.CharField(db_index=True, default='desktop', max_length=32)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='products.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['event_type', 'timestamp'], name='events_even_event_t_19b40a_idx'), models.Index(fields=['session_id', 'timestamp'], name='events_even_session_bf2c44_idx'), models.Index(fields=['user', 'timestamp'], name='events_even_user_id_2c2383_idx'), models.Index(fields=['product', 'event_type'], name='events_even_product_eda9fc_idx'), models.Index(fields=['device_type', 'event_type'], name='events_even_device__5f92b8_idx')],
            },
        ),
    ]
