# Generated by Django 6.0.8 on 2026-09-13 20:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('image_url', models.URLField(blank=True, default='', max_length=500)),
                ('icon_name', models.CharField(blank=True, default='Shirt', max_length=32)),
                ('display_order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('slug', models.SlugField(max_length=64)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='products.category')),
            ],
            options={
                'verbose_name_plural': 'SubCategories',
                'unique_together': {('category', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('brand', models.CharField(db_index=True, max_length=128)),
                ('description', models.TextField()),
                ('price', models.DecimalField(db_index=True, decimal_places=2, max_digits=10)),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_percentage', models.IntegerField(db_index=True, default=0)),
                ('rating', models.FloatField(db_index=True, default=4.0)),
                ('rating_count', models.IntegerField(default=100)),
                ('color', models.CharField(db_index=True, max_length=50)),
                ('available_sizes', models.JSONField(default=list)),
                ('stock', models.IntegerField(default=50)),
                ('delivery_days', models.IntegerField(db_index=True, default=3)),
                ('occasion', models.CharField(choices=[('Casual', 'Casual Wear'), ('Party', 'Party & Evening'), ('Formal', 'Work & Formal'), ('Wedding', 'Wedding & Festive'), ('Sports', 'Athletic & Sports'), ('Loungewear', 'Loungewear & Night')], db_index=True, default='Casual', max_length=50)),
                ('season', models.CharField(choices=[('Summer', 'Summer / Spring'), ('Winter', 'Winter / Fall'), ('All Season', 'All Season Essentials'), ('Monsoon', 'Monsoon Ready')], db_index=True, default='All Season', max_length=50)),
                ('material', models.CharField(db_index=True, default='Cotton', max_length=100)),
                ('popularity_score', models.FloatField(db_index=True, default=75.0)),
                ('image_url', models.URLField(max_length=1000)),
                ('additional_images', models.JSONField(blank=True, default=list)),
                ('is_trending', models.BooleanField(db_index=True, default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category')),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.subcategory')),
            ],
            options={
                'ordering': ['-popularity_score', '-rating'],
                'indexes': [models.Index(fields=['category', 'price'], name='products_pr_categor_47b724_idx'), models.Index(fields=['brand', 'rating'], name='products_pr_brand_d9f1cf_idx'), models.Index(fields=['occasion', 'season'], name='products_pr_occasio_408932_idx')],
            },
        ),
    ]
