# Generated by Django 6.0.8 on 2026-09-13 20:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('key', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('control_name', models.CharField(default='control_keyword', max_length=50)),
                ('treatment_name', models.CharField(default='treatment_ai_search', max_length=50)),
                ('traffic_split_percent', models.IntegerField(default=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_returning', models.BooleanField(default=False)),
                ('segment', models.CharField(choices=[('new', 'New Visitor'), ('budget', 'Budget Conscious (< ₹1500)'), ('trendsetter', 'Trendsetter & High Intent'), ('luxury', 'Premium / Luxury (> ₹4000)'), ('occasional', 'Occasional Shopper')], default='new', max_length=32)),
                ('preferred_device', models.CharField(default='mobile', max_length=16)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('session_id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('device_type', models.CharField(db_index=True, default='mobile', max_length=32)),
                ('experiment_variant', models.CharField(db_index=True, default='control_keyword', max_length=64)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('referrer', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('last_active', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
